name: rescan-codescan-sarif-manual

on: workflow_dispatch

jobs:
  wait_for:
    name: Wait for any issues, gh-int + code_scanning_alerts on
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      id-token: write
    steps:
      - name: Scan Start
        id: start
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN}}
          hostname: app.brightsec.com
          name: Bright Scan - ${{ github.sha }}
          restart_scan: ${{ secrets.BRIGHT_SCANIDMULT}}
      - name: Wait for breakpoint
        id: wait
        uses: NeuraLegion/wait-for@release
        with:
          api_token:  ${{ secrets.BRIGHT_TOKEN }}
          hostname: app.brightsec.com
          scan: ${{ steps.start.outputs.id }}
          wait_for: high
          code_scanning_alerts: false
          github_token: ${{ secrets.KEY_GITHUB }}
          timeout: 600
      - name: Download SARIF file
        id: sarif
        env:
          api_token: ${{ secrets.BRIGHT_TOKEN }}
          scanId: ${{ steps.start.outputs.id }}
        run: |
          echo Downloading sarif report
          curl -X GET "https://app.brightsec.com/api/v1/scans/$scanId/reports/sarif" -H "Authorization: Api-Key $api_token" -o bright.sarif.gz
          gzip -d bright.sarif.gz
          sarifFileText=$(cat bright.sarif)
          echo "sarif file text: $sarifFileText"
      - name: Upload SARIF file - No GHAS
        uses: actions/upload-artifact@v4
        with: 
          name: BrightSecurity_Report_${{ github.run_id }}
          path: bright.sarif
      - name: Upload results to MSDO
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          existingFilename: bright.sarif
